### ISSUE TITLE
Casing Issues and Custom Fields

### ISSUE THREAD

**Issue by sperand-io** [segment-integrations/integration-appboy#6]
Current:

![](https://cloudup.com/c5u9vaTAh9s+)

>"It appears the problem is that Segment isn't passing that data to us via our standard attribute naming conventions. If you look for example, they're sending us "Name" : "Daniel" when in order to log that appropriately to our user profile, they should be sending that as "first_name" : "Daniel". The full list of standard profile fields is linked here (https://documentation.appboy.com/REST_APIs/User_Data#user-profile-fields)."

>**"The data is still getting to Appboy, but it's being logged as a custom attribute since it's not coming in the format that we would expect.**"

https://segment.zendesk.com/agent/tickets/27441

**Comment by prestonwrthompson** [comment]
I don't really think this is an issue. The user should be using the standard conventions that either Appboy or Segment offers. If any of the standard Segment user traits (which require camelCase) are used that translate into Appboy profile fields, the integration will currently use those. If the user traits are passed using our naming conventions (using snake_case), the integration will use those. The user is using UpperCamelCase, which neither of our services recognize.

**Comment by hankim813** [comment]
No longer an issue: https://github.com/segment-integrations/integration-appboy/blob/master/lib/mapper.js#L111-L121
